majorPattern: "(?:^.+\!:.*$|(?m)^BREAKING CHANGE:.*$)"
minorPattern: "^(?:feat|chore|build|ci|refactor|perf)(?:\(.+\))?:.*$"
bumpStrategies:
  - branchesPattern: "^(main|master|release/.*)$"
    strategy: "AUTO"
    preRelease: false
    preReleaseTemplate:
    preReleaseOverwrite: false
    buildMetadataTemplate:
  - branchesPattern: ".*"
    strategy: "AUTO"
    preRelease: false
    preReleaseTemplate:
    preReleaseOverwrite: false
    buildMetadataTemplate: "{{.Commits | len}}.{{(.Commits | first).Hash.Short}}"